spring:
  application:
    name: user-service

  #r2dbc (database webflux)
  r2dbc:
    url: r2dbc:pool:postgresql://localhost:2346/user_db
    password: user
    username: user
  profiles:
    active: dev

server:
  port: 8082